version: '3.5'

services:
  app:
    tty: true
    container_name: app_container
    restart: always
    networks:
      - statistics_gather_network
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}

networks:
  statistics_gather_network:
    name: statistics_gather
    external: true
